Style/chal
someone-to-speak/OnePeak pull request #109
Opened 2024-11-10 07:39 UTC by kimseoyun98

## 🔥 작업 내용

-
-

## 💁🏻‍♀️ 체크리스트
<img width="388" alt="스크린샷 2024-11-10 오후 4 35 11" src="https://github.com/user-attachments/assets/0f2db2da-6d6e-4e78-9eef-f86299fffb9f">
- 빈칸에 정답을 넣을수 없어서 디자인 변경

## 👍 참고 사항

-
-

## 📸 빌드 캡쳐 내역
<img width="554" alt="스크린샷 2024-11-10 오후 4 38 08" src="https://github.com/user-attachments/assets/5c91496f-ed1a-454b-85b5-18f1deb01fb6">

2024-11-10 15:39 UTC, soo0297 requested changes

2024-11-10 15:39 UTC, soo0297 commented on src/components/wrongAnswer/WordList.tsx
> +const GrammarList = ({ userId }: { userId: string }) => {
파일이름은 WordList인데 GrammarList로 바꾸신 이유가 어떤 것일까요? 잘못 수정하신 것 같은데 확인 후 수정 부탁드릴게요~

2024-11-11 00:40 UTC, kimseoyun98 commented on src/components/wrongAnswer/WordList.tsx
> +const GrammarList = ({ userId }: { userId: string }) => {
오 감사합니다!

2024-11-11 02:58 UTC, soo0297 approved these changes
변경해주신 부분 확인했습니다!

2024-11-11 03:06 UTC, merged